[Feature] Support PointRCNN RPN and RCNN module
open-mmlab/mmdetection3d pull request #1022
Opened 2021-11-01 03:55 UTC by wHao-Wu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
Support PointRCNN RPN and RCNN module to support the complete PointRCNN detector.

## Modification
Support PointRCNN RPN and RCNN module.

## BC-breaking (Optional)
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2021-11-03 09:26 UTC, ZwwWayne commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +        sem_scores = F.sigmoid(cls_preds)
cls_preds.sigmoid()

2021-11-03 09:30 UTC, ZwwWayne commented on mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py
> +        abs_error = torch.abs(corner_dist)
corner_dist.abs()
abs_error.clamp(max=delta)

2021-11-03 09:30 UTC, ZwwWayne commented on mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py
> +            opposite_flag = (ry_label > np.pi * 0.5) & (ry_label < np.pi * 1.5)
opposite_flag?

2021-11-03 09:34 UTC, ZwwWayne commented on mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py
> +        selected = torch.cat(
selected -> keep

2021-11-10 06:46 UTC, ZCMax commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +        return 3 + 3 + 2
change hard code to parameters?

2021-11-10 07:08 UTC, ZCMax commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +            nn.Sequential: fully connect layers.
Fully

2021-11-10 09:11 UTC, Tai-Wang commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +        nms_selected = batched_nms(
Check whether the nms considers rotations.

2021-11-10 13:00 UTC, Tai-Wang requested changes

2021-11-22 08:18 UTC, wHao-Wu commented on configs/_base_/models/point_rcnn.py
> +find_unused_parameters = True
The model cannot be trained successfully after removing this parameter.

2021-11-22 09:22 UTC, wHao-Wu commented on mmdet3d/models/roi_heads/point_rcnn_roi_head.py
> +            # 0 is bg
It is consistent with `mmdet3d/models/roi_heads/part_aggregation_roi_head.py`.

2021-11-23 12:39 UTC, Tai-Wang commented on configs/pointrcnn/README.md
> +@InProceedings{Shi_2019_CVPR,
shi2019pointrcnn is a general annotation.

2021-11-23 12:43 UTC, Tai-Wang commented on mmdet3d/models/dense_heads/ssd_3d_head.py
> +        """Generate bboxes from ssd3d head predictions.
3DSSD?

2021-11-23 12:48 UTC, Tai-Wang commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +        object_class = torch.argmax(sem_scores, -1)
sem_scores.argmax(xxx)

2021-12-01 07:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmdetection3d?pullRequest=1022) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmdetection3d?pullRequest=1022) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: xiliu8006<br/>:white_check_mark: THU17cyz<br/>:white_check_mark: wHao-Wu<br/>:white_check_mark: Tai-Wang<br/>:white_check_mark: ZCMax<br/>:x: zhuchenming<br/><hr/>**zhuchenming** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmdetection3d?pullRequest=1022) it.</sub>

2021-12-01 14:45 UTC, ZwwWayne approved these changes

2021-12-02 06:37 UTC, ZCMax approved these changes

2021-12-02 07:47 UTC, wHao-Wu commented on mmdet3d/models/detectors/pointrcnn.py
> +    def forward_train(self, points, img_metas, gt_bboxes_3d, gt_labels_3d):
I will keep the `img_metas` to keep consistent with other detectors, like [imvotenet](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0.dev0/mmdet3d/models/detectors/imvotenet.py#L370), [votenet](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0.dev0/mmdet3d/models/detectors/votenet.py#L30), [h3dnet](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0.dev0/mmdet3d/models/detectors/h3dnet.py#L37), etc.

2021-12-02 12:10 UTC, Machine97 commented
Thank you for your contribution. When I try to train PointRCNN as you did, it get stuck in the first epoch during training, and no error warning. Can you help me to solve this problem?

2021-12-03 02:37 UTC, wHao-Wu commented
Hi, @Machine97 
Thanks for your attention. For training PointRCNN successfully, you may meet the prerequisites as follows:
1. Please pull and install the latest [mmcv](https://github.com/open-mmlab/mmcv) and [mmdetection](https://github.com/open-mmlab/mmdetection).
2. If you generate KITTI data using the master branch, please regenerate KITTI data using the v1.0.0.dev0 branch.
3. Please install the mmdetection3d instructed by [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) with the v1.0.0.dev0 branch instead of the master branch.

2021-12-06 02:24 UTC, wHao-Wu commented on configs/_base_/models/point_rcnn.py
> +find_unused_parameters = True
Thanks for your advice. I will fit this problem (which also appears in the PartA2 model) in another PR.

2021-12-07 08:55 UTC, ZwwWayne commented on mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py
> +            losses['loss_bbox'] = loss_cls.new_tensor(0)
This part should be updated, otherwise it will cause hanging issues because the weights in head is not included in the loss calculation.

2021-12-07 09:03 UTC, ZwwWayne commented
> Thank you for your contribution. When I try to train PointRCNN as you did, it get stuck in the first epoch during training, and no error warning. Can you help me to solve this problem?

There is indeed an issue in the loss calculation when there is no positive sample. We will fix that in this PR.

2021-12-08 07:09 UTC, Tai-Wang commented on configs/_base_/models/point_rcnn.py
> +                dict(  # for Pestrian
Pedestrian
Please re-install the pre-commit hook, should be corrected with the code-spell hook?

2021-12-08 07:10 UTC, Tai-Wang commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +    def forward(self, feat_dict):
docstring

2021-12-08 07:11 UTC, Tai-Wang commented on mmdet3d/models/detectors/point_rcnn.py
> +    Please refer to the `PointRCNN https://arxiv.org/abs/1812.04244`_
Check the reference format, lack \<>

2021-12-08 08:12 UTC, Tai-Wang commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +            tuple:
tuple[list[torch.Tensor]]: Predicted boxes and classification scores.

2021-12-08 08:12 UTC, Tai-Wang commented on mmdet3d/models/dense_heads/point_rpn_head.py
> +            tuple:
Do not need variable names

2021-12-08 09:03 UTC, Tai-Wang approved these changes

2021-12-08 15:21 UTC, merged

2021-12-14 07:51 UTC, Machine97 commented
Hi, all. Thank you for your contribution. I want to ask have you complished the PointRCNN and what's the detailed results?

2021-12-14 08:29 UTC, Machine97 commented
> Hi, @Machine97 Thanks for your attention. For training PointRCNN successfully, you may meet the prerequisites as follows:
> 
> 1. Please pull and install the latest [mmcv](https://github.com/open-mmlab/mmcv) and [mmdetection](https://github.com/open-mmlab/mmdetection).
> 2. If you generate KITTI data using the master branch, please regenerate KITTI data using the v1.0.0.dev0 branch.
> 3. Please install the mmdetection3d instructed by [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) with the v1.0.0.dev0 branch instead of the master branch.

Thank you for your reply. I'm sorry to reply so late. I want to ask if I build an image according to the v1.0.0.dev0 branch Dockerfile, then train the PointRCNN. Is that ok?

2021-12-14 15:20 UTC, Machine97 commented
> > Hi, @Machine97 Thanks for your attention. For training PointRCNN successfully, you may meet the prerequisites as follows:
> > 
> > 1. Please pull and install the latest [mmcv](https://github.com/open-mmlab/mmcv) and [mmdetection](https://github.com/open-mmlab/mmdetection).
> > 2. If you generate KITTI data using the master branch, please regenerate KITTI data using the v1.0.0.dev0 branch.
> > 3. Please install the mmdetection3d instructed by [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) with the v1.0.0.dev0 branch instead of the master branch.
> 
> Thank you for your reply. I'm sorry to reply so late. I want to ask if I build an image according to the v1.0.0.dev0 branch Dockerfile, then train the PointRCNN. Is that ok?

I tried like this. However, it get stuck at the begining.
![GTW03{{FK}64B{XJKH$J4WN](https://user-images.githubusercontent.com/53359490/146026634-11e132c6-2c2e-4011-9b3c-13b129a0220a.png)

2021-12-14 15:25 UTC, Machine97 commented
> > Hi, @Machine97 Thanks for your attention. For training PointRCNN successfully, you may meet the prerequisites as follows:
> > 
> > 1. Please pull and install the latest [mmcv](https://github.com/open-mmlab/mmcv) and [mmdetection](https://github.com/open-mmlab/mmdetection).
> > 2. If you generate KITTI data using the master branch, please regenerate KITTI data using the v1.0.0.dev0 branch.
> > 3. Please install the mmdetection3d instructed by [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) with the v1.0.0.dev0 branch instead of the master branch.
> 
> Thank you for your reply. I'm sorry to reply so late. I want to ask if I build an image according to the v1.0.0.dev0 branch Dockerfile, then train the PointRCNN. Is that ok?

I tried like this. However, it get stuck at the begining, and no error warning. I don't know why. By the way,  I generate KITTI data using the master branch and not the v1.0.0.dev0 branch, is this the cause of the error?

2021-12-15 02:09 UTC, Machine97 commented
> > Hi, @Machine97 Thanks for your attention. For training PointRCNN successfully, you may meet the prerequisites as follows:
> > 
> > 1. Please pull and install the latest [mmcv](https://github.com/open-mmlab/mmcv) and [mmdetection](https://github.com/open-mmlab/mmdetection).
> > 2. If you generate KITTI data using the master branch, please regenerate KITTI data using the v1.0.0.dev0 branch.
> > 3. Please install the mmdetection3d instructed by [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) with the v1.0.0.dev0 branch instead of the master branch.
> 
> Thank you for your reply. I'm sorry to reply so late. I want to ask if I build an image according to the v1.0.0.dev0 branch Dockerfile, then train the PointRCNN. Is that ok?

I tried to train PointRCNN like this, but it get stuck at the begining during training and no error warning. I'm confused about this. The following picture is the stucked position.
![{%LU{U%EHLO`FQCY4Z9Y M2](https://user-images.githubusercontent.com/53359490/146110074-847e8104-74ac-40c5-b477-e095aafad3eb.png)

2021-12-15 02:31 UTC, Machine97 commented
Now this error has occurred.
![image](https://user-images.githubusercontent.com/53359490/146112199-f02ac0fa-4350-4459-9402-52216ff6d665.png)

2021-12-15 03:35 UTC, Machine97 commented
@wHao-Wu @Tai-Wang @ZwwWayne 
Another question. I change an enviroment and train the PointRCNN sucessfully. But in the processing of training, it occur the following error. It seems that variable grad_norm is unstable. I don't know what the purpose of the variable grad_norm is. Can you give me some advice to solve this problem? Thank you so much.
![image](https://user-images.githubusercontent.com/53359490/146118211-b4ecdef0-0a1f-4dc5-88b9-822eca010897.png)

2021-12-15 03:36 UTC, Machine97 commented
@wHao-Wu @ZwwWayne @Tai-Wang 
Another question. I change an enviroment and train the PointRCNN sucessfully. But in the processing of training, it occur the following error. It seems that variable grad_norm is unstable. I don't know what the purpose of the variable grad_norm is. Can you give me some advice to solve this problem? Thank you so much.
![image](https://user-images.githubusercontent.com/53359490/146118642-a4369f1a-25a8-4505-a602-1ed8846ae86e.png)

2021-12-15 07:49 UTC, Machine97 commented
> @wHao-Wu @ZwwWayne @Tai-Wang Another question. I change an enviroment and train the PointRCNN sucessfully. But in the processing of training, it occur the following error. It seems that variable grad_norm is unstable. I don't know what the purpose of the variable grad_norm is. Can you give me some advice to solve this problem? Thank you so much. ![image](https://user-images.githubusercontent.com/53359490/146118642-a4369f1a-25a8-4505-a602-1ed8846ae86e.png)

@wHao-Wu @CLAassistant @ZwwWayne @Tai-Wang Hi, all.
In order to find the reason for this error, I add some code as shown in the figure below in /mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py.
![image](https://user-images.githubusercontent.com/53359490/146144504-183f6cc5-6546-4746-8905-0e4b30e2ab02.png)
Then, after training, the results shown in the figure below appear. The error seems to come from the variable 'cls_score', can you give me some advice to solve this problem?
![BMS8 8W@@8XI7ND8 R~9)SY](https://user-images.githubusercontent.com/53359490/146144559-8461664b-cf40-4eb6-b695-d93fedf03d82.png)

2021-12-16 07:58 UTC, wHao-Wu commented
> > Hi, @Machine97 Thanks for your attention. For training PointRCNN successfully, you may meet the prerequisites as follows:
> > 
> > 1. Please pull and install the latest [mmcv](https://github.com/open-mmlab/mmcv) and [mmdetection](https://github.com/open-mmlab/mmdetection).
> > 2. If you generate KITTI data using the master branch, please regenerate KITTI data using the v1.0.0.dev0 branch.
> > 3. Please install the mmdetection3d instructed by [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) with the v1.0.0.dev0 branch instead of the master branch.
> 
> Thank you for your reply. I'm sorry to reply so late. I want to ask if I build an image according to the v1.0.0.dev0 branch Dockerfile, then train the PointRCNN. Is that ok?

Hi, @Machine97 
Thanks for your attention and sorry for the late reply. You can build an image of v1.0.0.dev0 branch based on the Dockerfile [here](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0.dev0/docker/Dockerfile).

2021-12-16 08:00 UTC, wHao-Wu commented
> @wHao-Wu @ZwwWayne @Tai-Wang Another question. I change an enviroment and train the PointRCNN sucessfully. But in the processing of training, it occur the following error. It seems that variable grad_norm is unstable. I don't know what the purpose of the variable grad_norm is. Can you give me some advice to solve this problem? Thank you so much. ![image](https://user-images.githubusercontent.com/53359490/146118642-a4369f1a-25a8-4505-a602-1ed8846ae86e.png)

Could you please post your training log here or [issue](https://github.com/open-mmlab/mmdetection3d/issues/1118).

2021-12-16 08:14 UTC, Machine97 commented
> > @wHao-Wu @ZwwWayne @Tai-Wang Another question. I change an enviroment and train the PointRCNN sucessfully. But in the processing of training, it occur the following error. It seems that variable grad_norm is unstable. I don't know what the purpose of the variable grad_norm is. Can you give me some advice to solve this problem? Thank you so much. ![image](https://user-images.githubusercontent.com/53359490/146118642-a4369f1a-25a8-4505-a602-1ed8846ae86e.png)
> 
> Could you please post your training log here or [issue](https://github.com/open-mmlab/mmdetection3d/issues/1118)?

Hi, thank you so much for your reply.
I changed the learning rate from 0.001 to 0.0005 and it can train normally so far. By the way, I train the PointRCNN followed the configs in configs/point_rcnn/point_rcnn_2x8_kitti-3d-3classes.py with train+val data and modified the batchsize from 2 to 3, modified the lr from 0.001 to 0.0005, the rest keep as origin.
It has trained to the 12th epoch so far, the eval results are shown in the figure below. The accuracy is relatively low, is this normal? I use train+val data to train and val data to test.
![image](https://user-images.githubusercontent.com/53359490/146333238-d944a36c-247b-4c61-95dc-e14e7297d1f3.png)

2021-12-17 05:19 UTC, wHao-Wu commented
@Machine97 
It must be something wrong in this setting. In my case, I can get `66.6342` for `Car`, `41.8122` for `Pedestrian`, and `61.7294` for `Cyclist`. We have supported PointRCNN benchmark on the KITTI dataset. You can refer to [here](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0.dev0/configs/point_rcnn) to find the log file for more details. Next, we will try to reproduce your problem. Thanks for your feedback.

2021-12-17 11:28 UTC, Machine97 commented
> @Machine97 It must be something wrong in this setting. In my case, I can get `66.6342` for `Car`, `41.8122` for `Pedestrian`, and `61.7294` for `Cyclist`. We have supported PointRCNN benchmark on the KITTI dataset. You can refer to [here](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0.dev0/configs/point_rcnn) to find the log file for more details. Next, we will try to reproduce your problem. Thanks for your feedback.

@wHao-Wu 
Thank you for your reply. This is my train log.
[20211217_104132.log](https://github.com/open-mmlab/mmdetection3d/files/7734711/20211217_104132.log)
I trained on 4GPUs. In the train log, the AP is very low and we can find that 'loss_cls' are gradually increasing. It must be something wrong. I'm so confused about it.

2021-12-18 09:26 UTC, Machine97 commented
@wHao-Wu 
Hi, could you please help me to find out where the mistake happened?

2021-12-20 02:57 UTC, wHao-Wu commented
> > @Machine97 It must be something wrong in this setting. In my case, I can get `66.6342` for `Car`, `41.8122` for `Pedestrian`, and `61.7294` for `Cyclist`. We have supported PointRCNN benchmark on the KITTI dataset. You can refer to [here](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0.dev0/configs/point_rcnn) to find the log file for more details. Next, we will try to reproduce your problem. Thanks for your feedback.
> 
> @wHao-Wu Thank you for your reply. This is my train log. [20211217_104132.log](https://github.com/open-mmlab/mmdetection3d/files/7734711/20211217_104132.log) I trained on 4GPUs. In the train log, the AP is very low and we can find that 'loss_cls' are gradually increasing. It must be something wrong. I'm so confused about it.

@Machine97 
Sorry for the late reply because of the time cost for issue-reproducing. I found that you haven't changed the LR to 0.0005 from your training log (the LR still keeps to 0.001). Then, I used your setting to reproduce your problem and cannot find any problem when training PointRCNN model. Detailed can be found [here](https://github.com/open-mmlab/mmdetection3d/files/7742278/20211219_122722.log). Besides, I also rerun PointRCNN with LR=0.0005 and GPUs=4 and the model also got normal [results](https://github.com/open-mmlab/mmdetection3d/files/7742262/20211217_173945.log).

There are some possible problems:
1. Please update your KITTI data with v1.0.0.dev0 if you use the master branch to generate KITTI data before.
2. Please pull the latest code from v1.0.0.dev0 branch and rerun the PointRCNN again.
3. If possible, please pull the latest `mmcv`, `mmdetection`.

2021-12-20 03:01 UTC, Machine97 commented
> > > @Machine97 It must be something wrong in this setting. In my case, I can get `66.6342` for `Car`, `41.8122` for `Pedestrian`, and `61.7294` for `Cyclist`. We have supported PointRCNN benchmark on the KITTI dataset. You can refer to [here](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0.dev0/configs/point_rcnn) to find the log file for more details. Next, we will try to reproduce your problem. Thanks for your feedback.
> > 
> > 
> > @wHao-Wu Thank you for your reply. This is my train log. [20211217_104132.log](https://github.com/open-mmlab/mmdetection3d/files/7734711/20211217_104132.log) I trained on 4GPUs. In the train log, the AP is very low and we can find that 'loss_cls' are gradually increasing. It must be something wrong. I'm so confused about it.
> 
> @Machine97 Sorry for the late reply because of the time cost for issue-reproducing. I found that you haven't changed the LR to 0.0005 from your training log (the LR still keeps to 0.001). Then, I used your setting to reproduce your problem and cannot find any problem when training PointRCNN model. Detailed can be found [here](https://github.com/open-mmlab/mmdetection3d/files/7742278/20211219_122722.log). Besides, I also rerun PointRCNN with LR=0.0005 and GPUs=4 and the model also got normal [results](https://github.com/open-mmlab/mmdetection3d/files/7742262/20211217_173945.log).
> 
> There are some possible problems:
> 
> 1. Please update your KITTI data with v1.0.0.dev0 if you use the master branch to generate KITTI data before.
> 2. Please pull the latest code from v1.0.0.dev0 branch and rerun the PointRCNN again.
> 3. If possible, please pull the latest `mmcv`, `mmdetection`.

Thank you so much for your reply. I will try according to your advice and give you a feedback as soon as possible.

2021-12-20 10:44 UTC, Machine97 commented
> > > @Machine97 It must be something wrong in this setting. In my case, I can get `66.6342` for `Car`, `41.8122` for `Pedestrian`, and `61.7294` for `Cyclist`. We have supported PointRCNN benchmark on the KITTI dataset. You can refer to [here](https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0.dev0/configs/point_rcnn) to find the log file for more details. Next, we will try to reproduce your problem. Thanks for your feedback.
> > 
> > 
> > @wHao-Wu Thank you for your reply. This is my train log. [20211217_104132.log](https://github.com/open-mmlab/mmdetection3d/files/7734711/20211217_104132.log) I trained on 4GPUs. In the train log, the AP is very low and we can find that 'loss_cls' are gradually increasing. It must be something wrong. I'm so confused about it.
> 
> @Machine97 Sorry for the late reply because of the time cost for issue-reproducing. I found that you haven't changed the LR to 0.0005 from your training log (the LR still keeps to 0.001). Then, I used your setting to reproduce your problem and cannot find any problem when training PointRCNN model. Detailed can be found [here](https://github.com/open-mmlab/mmdetection3d/files/7742278/20211219_122722.log). Besides, I also rerun PointRCNN with LR=0.0005 and GPUs=4 and the model also got normal [results](https://github.com/open-mmlab/mmdetection3d/files/7742262/20211217_173945.log).
> 
> There are some possible problems:
> 
> 1. Please update your KITTI data with v1.0.0.dev0 if you use the master branch to generate KITTI data before.
> 2. Please pull the latest code from v1.0.0.dev0 branch and rerun the PointRCNN again.
> 3. If possible, please pull the latest `mmcv`, `mmdetection`.

@wHao-Wu 
Hi, according to your suggestion, I took the following steps:
     1. Build an image of v1.0.0.dev0 branch based on the Dockerfile [https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0.dev0/docker/Dockerfile](url).
     2. Update my KITTI data with v1.0.0.dev0 by running /tools/create_data.py file.
     3. Pull the latest code from v1.0.0.dev0 branch and rerun the PointRCNN again.
However, there still be the same mistakes as before. I think this should not be an environment problem. I want to ask what's  the difference about the way of KITTI data generation in master and v1.0.0.dev0.

2021-12-20 11:18 UTC, Machine97 commented
@wHao-Wu 
Hi, I carefully compared the log file you provided with the latest code from v1.0.0.dev0 branch, there are some differences in /configs/_base_/models/point_rcnn.py, like 'enlarge_width=0.1' which doesn't appear in the log file you provided. So, would you please pull the latest code from v1.0.0.dev0 branch and rerun the PointRCNN again?
I look forward to your reply as soon as possible, and appreciate it.

2021-12-20 12:04 UTC, Machine97 commented
@wHao-Wu 
Hi, if I change the parameters in /configs/base/models/point_rcnn.py file as the log file you provided. It will appear another error showed in the following picture.
![image](https://user-images.githubusercontent.com/53359490/146764629-4440a6a2-216c-45a3-bd45-9d1c25074462.png)

2021-12-23 05:39 UTC, Machine97 commented
@wHao-Wu 
Hi, I'm so sorry to bother you again. Have you tried to pull the latest code from v1.0.0.dev0 branch and rerun the PointRCNN again?