[Enhance] add plane info in generated pkl file
open-mmlab/mmdetection3d pull request #1162
Opened 2022-01-10 06:52 UTC by ZCMax

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
This PR adds plane info in the generation process of pkl file. During the ablation study the ablation study of PointPillars on kitti, the ground plane infos is crucial for boosting the performance of models.  

## Modification
`tools/data_converter/kitti_data_infos.py` and `toools/data_converter/kitti_converter.py.`

## BC-breaking (Optional)
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-01-10 06:54 UTC, ZCMax commented
Besides, the training datasets planes txt file should be provided, and the docs about kitti preparation  should be changed.

2022-01-10 08:12 UTC, ZCMax commented
The docs has been modified, and the planes file has been provided.

2022-01-10 08:20 UTC, Tai-Wang commented on tools/data_converter/kitti_converter.py
> +        plane=True,
plane -> use_plane, also modify other arguments correspondingly

2022-01-10 08:22 UTC, Tai-Wang requested changes
Just need to fix comments

2022-01-19 07:45 UTC, ZCMax commented
The plane infomations are generated by `Ground segmentation and occupancy grid generation using probability fields`, and the link of the code generating the planes infos has been dead.

2022-01-25 09:20 UTC, ZwwWayne commented on tools/data_converter/kitti_data_utils.py
> +            with open(plane_path, 'r') as f:
can we use lines = mmcv.list_from_file(plane_path)

2022-01-27 06:59 UTC, ZCMax commented
@ZwwWayne

2022-02-09 09:26 UTC, ZwwWayne approved these changes

2022-02-09 09:26 UTC, merged