[Feaute]support spconv2.0
open-mmlab/mmdetection3d pull request #1421
Opened 2022-04-23 12:10 UTC by VVsssssk

## Motivation
Support spconv2.0 in mmdet3d dev branch.  If the user installed spconv2.0, the code would use spconv2.0 first. And if spconv2.0 is not installed, the code will use mmcv's spconv op.

## BC-breaking (Optional)
.

## Checklist

- [ ] fix get_start docs

2022-04-24 02:41 UTC, Tai-Wang commented on mmdet3d/ops/sparse_block.py
> +            out = out.replace_feature(self.relu(out.features))
These two lines are the only differences between if-else? May simplify the codes

2022-04-24 02:43 UTC, Tai-Wang commented on mmdet3d/ops/spconv/overwrite_spconv.py
> +def write_spconv():
may rename as overwrite_spconv/write_spconv2/register_spconv2

2022-04-27 07:19 UTC, Tai-Wang requested changes
Just need to fix minor comments.

2022-04-27 07:19 UTC, Tai-Wang commented on mmdet3d/ops/spconv/overwrite_spconv/write_spconv2.py
> +                          missing_keys, unexpected_keys, error_msgs):
Please add the corresponding docstring.

2022-04-27 07:19 UTC, Tai-Wang commented on mmdet3d/ops/spconv/overwrite_spconv/write_spconv2.py
> +    for name, param in self._parameters.items():
Is there any difference for spconv 1.0 and 2.0 when saving and loading checkpoints? Maybe need some comments or a brief docstring to summarize the differences.

2022-04-27 07:53 UTC, ZCMax commented on mmdet3d/ops/spconv/overwrite_spconv/write_spconv2.py
> +def register_spconv2():
Adding some docstring for explaining that Once spconv2.0 can be used, we need to register the spconv2.0 to overwrite the original spconv in mmcv.

2022-04-27 09:28 UTC, ZwwWayne commented on docs/en/getting_started.md
> +   We have supported spconv2.0. If you have installed spconv2.0, the code will use spconv2.0 first, and it has better performance. If necessary please refer to [spconv v2.x](https://github.com/travel
We have supported spconv2.0. If you have installed spconv2.0, the code will use spconv2.0 first, which could reduce the GPU memory. Users can use the following commands to install spconv2.0,
```bash
pip install cumm-cuxxx
pip install spconv-cuxxx
```
where `xxx` is the CUDA version in the environment.
For example, if you are using CUDA 10.2, the command will be `pip install cumm-cu102
 && pip install spconv-cu102`.
Supported CUDA versions include 10.2, 11.1, 11.3, 11.4. Users can also install it by building from source.
For more details please refer to [spconv v2.x](https://github.com/traveller59/spconv).

2022-04-27 09:28 UTC, ZwwWayne commented on mmdet3d/models/middle_encoders/sparse_encoder.py
> +from mmdet3d.ops.spconv import spconv2_is_avalible
is_spconv2_available

2022-04-27 09:32 UTC, ZwwWayne commented on mmdet3d/ops/spconv/overwrite_spconv/write_spconv2.py
> +                if input_name not in self._modules\
```
if input_name not in self._modules \
    and input_name not in local_state:
```

2022-04-27 09:33 UTC, ZwwWayne commented on mmdet3d/ops/spconv/overwrite_spconv/write_spconv2.py
> +                    'While copying the parameter named "{}", '
f-string

2022-04-27 15:14 UTC, ZwwWayne approved these changes

2022-04-27 15:16 UTC, ZwwWayne commented on mmdet3d/ops/spconv/overwrite_spconv/write_spconv2.py
> +    """Rewrite this func to resolve spconv ops kernel weights incompatible.
```python
"""Rewrite this func to compat the convolutional kernel weights between spconv 1.x in MMCV and 2.x in spconv2.x.

    Kernel weights in MMCV spconv has shape in (D,H,W,in_channel,out_channel), while those in spcon2.x
    is in (out_channel,D,H,W,in_channel).
"""
```

2022-04-28 05:09 UTC, ZwwWayne commented on mmdet3d/utils/collect_env.py
> +    env_info['spconv2.0 is avalible'] = IS_SPCONV2_AVAILABLE
spconv2.0 is avalible -> spconv2.0

2022-04-28 06:47 UTC, ZwwWayne approved these changes

2022-04-28 06:47 UTC, merged

2022-05-17 13:55 UTC, ammaryasirnaich commented
@VVsssssk, I have one question after training with the spconv2. If we use the `mmdet3d/apis/inference.py` for doing `inference_detector(model, pcd)` than which version will it choose spconV2 or V1? However, I think it's using V1 which is causing a dimensional mismatch with the trained weights!
I will really appreciate if you can confirm this, thanks