[Docs] Add docs and README for SPVCNN
open-mmlab/mmdetection3d pull request #2372
Opened 2023-03-21 03:27 UTC by sunjiahao1999

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Add docs and README for SPVCNN.

## BC-breaking (Optional)

Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2023-03-22 06:18 UTC, JingweiZhang12 approved these changes

2023-03-22 11:00 UTC, JingweiZhang12 approved these changes

2023-03-23 03:43 UTC, ZCMax commented on configs/spvcnn/README.md
> +We implement SPVCNN with TorchSparse backend and provide the result and checkpoints on SemanticKITTI datasets.
add a link for TorchSparse

2023-03-23 04:50 UTC, ZCMax commented on configs/spvcnn/README.md
> +**Note:** Due to TorchSparse backend, the model performance is relatively dependent on random seeds, and if random seeds are not specified the model performance will be different (± 1.5 mIoU).
The model performance is unstable with TorchSparse backend and may fluctuate by about 1.5 mIoU for different random seeds.

2023-03-29 01:12 UTC, Tai-Wang requested changes
Only need to revise the model/log links

2023-03-29 08:37 UTC, Tai-Wang approved these changes

2023-03-30 03:32 UTC, ZCMax approved these changes

2023-04-04 09:19 UTC, merged