[Docs] Add migration.md and notice for default branch switching
open-mmlab/mmdetection3d pull request #2407
Opened 2023-04-03 06:18 UTC by JingweiZhang12

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2023-04-04 03:13 UTC, ZCMax commented on README_zh-CN.md
> +
The type of link for migration guide doc is not unified in English and Chinese doc

2023-04-04 03:22 UTC, ZCMax commented on docs/en/migration.md
> +Along with the release of OpenMMLab 2.0, MMDetection3D (namely MMDet3D) 1.x made many significant changes, resulting in less redundant, more efficient code and a more consistent overall design. These
1.x -> 1.1

2023-04-04 03:25 UTC, ZCMax commented on docs/en/migration.md
> +MMDet3D 1.1 depends on the new foundational library for training deep learning models [MMEngine](https://github.com/open-mmlab/mmengine), and therefore has an entirely different dependency chain comp
Det3D 1.1 depends on the new foundational library [MMEngine](https://github.com/open-mmlab/mmengine) for training deep learning models,

2023-04-04 03:26 UTC, ZCMax commented on docs/en/migration.md
> +MMDet3D 1.1 depends on the new foundational library for training deep learning models [MMEngine](https://github.com/open-mmlab/mmengine), and therefore has an entirely different dependency chain comp
compared with MMDet3D 1.0 and 0.x

2023-04-04 03:27 UTC, ZCMax commented on docs/en/migration.md
> +MMDet3D 1.1 depends on the new foundational library for training deep learning models [MMEngine](https://github.com/open-mmlab/mmengine), and therefore has an entirely different dependency chain comp
Even if you have a well-rounded MMDet3D 1.0 / 0.x environment before

2023-04-04 03:32 UTC, ZCMax commented on docs/en/migration.md
> +You should update the annotation files generated in the old version since some key words and structures of annotation in MMDet3D 1.x have changed. The updating script is the following (taking KITTI a
Whether should we offer two guidance for users in 0.x and 1.0 respectively?

2023-04-04 03:39 UTC, ZCMax commented on docs/en/migration.md
> +MMDet3D 1.x supports loading weights trained by the old version. For models that are important or highly used, we totally verified the precision of them in the 1.x version. Espectially for some model
1.x -> 1.1

2023-04-04 03:52 UTC, ZCMax commented on docs/en/migration.md
> +MMDet3D 1.x supports loading weights trained by the old version. For models that are important or highly used, we totally verified the precision of them in the 1.x version. Espectially for some model
MMDet3D 1.1 now supports loading weights trained by the old version (1.0 version). For models that are important or frequently used, we have thoroughly verified their precision in the 1.1 version. Especially for certain models like [[centerpoint](https://github.com/open-mmlab/mmdetection3d/issues/2390)](https://github.com/open-mmlab/mmdetection3d/issues/2390)https://github.com/open-mmlab/mmdetection3d/issues/2390) that may experience potential performance drops or training bugs in the old version, we have checked and ensured their accuracy in the new version. If you encounter any problems, please feel free to raise an [[Issue](https://github.com/open-mmlab/mmdetection3d/issues)](https://github.com/open-mmlab/mmdetection3d/issues). Additionally, we have added some of the latest SOTA methods into our [[package](https://github.com/open-mmlab/mmdetection3d/configs/)](../../configs/) and [[projects](https://github.com/open-mmlab/mmdetection3d/projects/)](../../projects/), making MMDet3D 1.1 a highly recommended choice for implementing your project.

2023-04-04 08:12 UTC, ZCMax commented on docs/en/migration.md
> +MMDet3D 1.1 depends on the new foundational library for training deep learning models [MMEngine](https://github.com/open-mmlab/mmengine), and therefore has an entirely different dependency chain comp
MMDet3D 1.1 depends on the new foundational library [MMEngine](https://github.com/open-mmlab/mmengine)  for training deep learning models

2023-04-04 08:13 UTC, ZCMax commented on docs/en/migration.md
> +If your annotation files are generated in the 0.x version, you should firstly update them to 1.0 version using this [script](../../tools/update_data_coords.py). Alternatively, you can re-genetate ann
use -> using

2023-04-04 10:01 UTC, Tai-Wang commented on docs/en/migration.md
> +MMDet3D 1.1 supports loading weights trained by the old version (1.0 version). For models that are important or frequently used, we have thoroughly verified the precision of them in the 1.1 version.
Especially

2023-04-04 10:03 UTC, Tai-Wang requested changes
Please use Grammarly (at least as a plug-in) to check and polish the writing

2023-04-04 11:38 UTC, ZCMax approved these changes

2023-04-06 06:07 UTC, Tai-Wang approved these changes

2023-04-06 08:16 UTC, merged