[Enhance] Move train_cfg test_cfg to model
open-mmlab/mmdetection3d pull request #307
Opened 2021-02-15 13:04 UTC by xiliu8006

Move train_cfg/test_cfg into model in model configs

2021-02-18 14:23 UTC, Tai-Wang approved these changes

2021-02-19 05:35 UTC, ZwwWayne commented on configs/centerpoint/centerpoint_0075voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py
> +    pts_voxel_layer=dict(
Do we need lines 7-12?

2021-02-19 05:36 UTC, ZwwWayne commented on configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py
> +    pts_voxel_layer=dict(
Do we need lines 7-9?

2021-02-19 05:36 UTC, ZwwWayne commented on configs/centerpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py
> +    pts_voxel_layer=dict(point_cloud_range=point_cloud_range),
Do we need lines 6-7

2021-02-21 05:45 UTC, ZwwWayne commented
Please also modify the documentation.

2021-02-21 12:43 UTC, ZwwWayne commented on tools/train.py
> +        cfg.model, train_cfg=cfg.model.train_cfg, test_cfg=cfg.model.test_cfg)
Can we directly use `cfg.model` without setting train_cfg and test_cfg?

2021-02-21 12:44 UTC, ZwwWayne commented
Add migration section for the config refactoring like [here](https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/config.md#deprecated-train_cfgtest_cfg).

2021-02-23 09:36 UTC, ZwwWayne requested changes

2021-02-23 14:02 UTC, merged