[Feature] Support nuimages visualization
open-mmlab/mmdetection3d pull request #408
Opened 2021-04-05 09:33 UTC by xiliu8006

Support nuimages visualization

2021-04-06 08:05 UTC, ZwwWayne commented on mmdet3d/apis/test.py
> +                batch_size = len(result)
Add comment here indicating where is this logic adopted from and what is it for.

2021-04-07 01:59 UTC, Tai-Wang commented on mmdet3d/apis/test.py
> +                model.module.show_results(data, result, out_dir)
`show_results` and `show_result` are so confusing here. Please at least add a comment to explain the former is for visualization in mmdet3d (maybe multi-modality visualization in the future).

2021-04-07 02:00 UTC, Tai-Wang requested changes
Just need to add some supplementary comments.

2021-04-07 09:56 UTC, ZwwWayne commented on mmdet3d/apis/test.py
> +            if hasattr(model.module, 'show_results'):
Should use `isinstance` to determine whether the detector is a 2D detector or a 3D detector.

2021-04-07 09:57 UTC, ZwwWayne approved these changes

2021-04-07 09:57 UTC, merged