[Docs] Chinese Document of 2_new_data_model
open-mmlab/mmdetection3d pull request #729
Opened 2021-07-12 12:18 UTC by wHao-Wu

* Add Chinese Document of 2_new_data_model
* Fix a typo error of English Document of 2_new_data_model

2021-07-13 12:11 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +**注意**：考虑到 Waymo 数据集的格式与现有的其他数据集的格式的差别较大，因此本文以该数据集为例来讲解如何自定义数据集，从而方便理解数据集自定义的过程。若需要创建的新数据集与现有的数据集的组织格式较为相似，如 Lyft 数据集和 nuScenes 数据集，采用对数据集的中间格式进行转换的方式（第二种方式）而不是采用对数据格式进行转换的方式（第一种方式）更加简单易行。
采用对数据集的中间格式进行转换的方式（第二种方式）而不是采用对数据格式进行转换的方式（第一种方式）更加简单易行。-> 采用对数据集的中间格式进行转换的方式（第二种方式）相比于采用对数据格式进行转换的方式（第一种方式）会更加简单易行。

2021-07-13 12:13 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +具体来说，首先使用[数据转换器](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/waymo_converter.py)将 Waymo 数据集转换成 KITTI 数据集的格式，并定义 [Waymo 类]((https://github.com/open-mmlab/mmdetection3d
因此可以比较容易实现从 KittiDataset 类到 WaymoDataset 类的继承->因此可以比较容易通过继承 KittiDataset 类来实现 WaymoDataset 类

2021-07-13 12:16 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +第二步是准备配置文件来帮助数据集的读取和使用，另外，配置文件也能够帮助调整超参数从而获得较优的 3D 检测性能。
另外，为了在 3D 检测中获得不错的性能，调整超参数通常是必要的。

2021-07-13 12:16 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +## 训练一个新的模型
need a blank line

2021-07-13 12:17 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +更多的的使用细节，请参考 [Case 1](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html)。
请参考案例1

2021-07-13 12:17 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +更多有关测试和推理的使用细节，请参考 [Case 1]((https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html))。
请参考案例1

2021-07-13 12:20 UTC, Tai-Wang commented on docs/2_new_data_model.md
> +## KITTI dataset format
Just keep it as a subtitle under "Prepare the customized dataset". It is only an example under that instead of a parallel section.

2021-07-13 12:21 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +## KITTI 数据集格式
如上所述将其作为一个子标题 而非和“准备自定义数据集”并列的标题

2021-07-19 13:13 UTC, THU17cyz commented on docs_zh-CN/2_new_data_model.md
> +   1    type         Describes the type of object: 'Car', 'Van', 'Truck',
这些感觉应该翻译？

2021-07-19 13:13 UTC, THU17cyz commented on docs_zh-CN/2_new_data_model.md
> +更多有关测试和推理的使用细节，请参考 [案例 1]((https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html)) 。
多余的()

2021-07-21 06:06 UTC, wHao-Wu commented
Need more reviews on the description of KITTI data format.

2021-07-21 07:44 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +应用于 3D 目标检测的 KITTI 原始数据集的组织方式通常如下所示，其中 `ImageSets` 包含数据集划分文件，用以划分训练集/验证集/测试集，`calib` 包含针对 KITTI 数据集的校准信息文件，`image_2` 和 `velodyne` 分别包含图像数据和点云数据，`label_2` 包含与 3D 目标检测相关的标注文件。
\`calib\` 包含针对 KITTI 数据集的校准信息文件 -> \`calib\` 包含对于每个数据样本的标定信息

2021-07-21 07:47 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +KITTI 官方提供的目标检测开发[工具包]((https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_object.zip))详细描述了 KITTI 数据集的标注格式，例如，KITTI 标注格式包含了以下的标注信息：
工具包后面的链接有问题，多了一个括号。之后可以看下 readme preview 检查一遍这种细节。

2021-07-21 07:47 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +具体来说，首先使用[数据转换器](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/waymo_converter.py)将 Waymo 数据集转换成 KITTI 数据集的格式，并定义 [Waymo 类]((https://github.com/open-mmlab/mmdetection3d
Waymo 类的链接也多了一个括号而失效

2021-07-21 07:48 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +更多的的使用细节，请参考 [案例 1](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html) 。
更多的使用细节

2021-07-21 07:49 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +更多的的使用细节，请参考 [案例 1](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html) 。
\[案例 1\] 前面多了个空格

2021-07-21 07:49 UTC, Tai-Wang commented on docs_zh-CN/2_new_data_model.md
> +更多有关测试和推理的使用细节，请参考 [案例 1](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html) 。
\[案例 1\] 前面多了个空格

2021-07-21 13:19 UTC, wHao-Wu commented on docs_zh-CN/2_new_data_model.md
> +   1    类型      描述检测目标的类型：'Car'，'Van'，'Truck'，
@Tai-Wang 
描述  KITTI 数据集格式的这个部分需要做进一步修改吗？实际上，中文的描述部分的第一个字很难对齐，可能有点不美观

2021-08-25 08:44 UTC, Tai-Wang requested changes

2021-09-15 09:05 UTC, ZwwWayne approved these changes

2021-09-15 09:05 UTC, ZwwWayne approved these changes

2021-09-15 09:06 UTC, merged